blazegraph:
  service-url: http://blazegraph:8080/bigdata
  use-lbs: false

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 9000
  servlet:
    context-path:

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false
    # web-application-type: NONE
