blazegraph:
  service-url: http://blazegraph:8080/bigdata
  use-lbs: false

logging:
  level:
    root: INFO
    org.springframework.cloud.bus: DEBUG

management:
  endpoint:
    health:
      enabled: true
      showDetails: always
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  server:
    port: 8000

server:
  port: 9000
  servlet:
    context-path:

spring:
  main:
    lazy-initialization: false
