blazegraph:
  service-url: http://blazegraph:8080/bigdata
  use-lbs: false

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false
    web-application-type: NONE
