blazegraph:
  service-url: http://blazegraph:8080/bigdata
  use-lbs: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true

spring:

  application:
    name: triplestore

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false
    web-application-type: NONE
