logging:
  level:
    root: INFO

management:
  endpoint:
    health:
      enabled: true
      showDetails: always
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  server:
    port: 8000

server:
  port: 9000
  servlet:
    context-path: