ldpath:
  name: Articulorum Web API
  namespace: http://api:8080
  default-expiry: 5
  cache-location: cache

server:
  port: 8081
  servlet:
    context-path:

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true

spring:

  application:
    name: ldpath

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  devtools:
    add-properties: false
    restart:
      enabled: true

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false