ldpath:
  name: Articulorum Web API
  namespace: http://ldp:9000/api
  default-expiry: 5
  cache-location: cache

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

server:
  port: 9000
  servlet:
    context-path:

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false