server:
  port: 8081
  servlet:
    context-path:

spring:

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

  devtools:
    add-properties: false
    restart:
      enabled: true