ldpath:
  name: Articulorum Web API
  namespace: http://api:8080
  default-expiry: 5
  cache-location: cache

server:
  port: 8081
  servlet:
    context-path:

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  devtools:
    add-properties: false
    restart:
      enabled: true

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false