server:
  port: 8080
  servlet:
    context-path: 

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  datasource:
    platform: h2
    url: jdbc:h2:./articulorum;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: articulorum
    password: articulorum

  devtools:
    add-properties: false
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        web-allow-others: false

  jackson:
    serialization:
      indent-output: true

  jms:
    pub-sub-domain: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  main:
    lazy-initialization: true