logging:
  level:
    root: INFO
    org.springframework.cloud.bus: DEBUG

management:
  endpoint:
    health:
      enabled: true
      showDetails: always
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info
  server:
    port: 8000

server:
  port: 9000
  servlet:
    context-path:

spring:
  datasource:
    platform: h2
    url: jdbc:h2:./articulorum;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: articulorum
    password: articulorum

  h2:
    console:
      enabled: true
      path: /h2console
      settings:
        web-allow-others: false

  jackson:
    serialization:
      indent-output: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false

  main:
    lazy-initialization: true