server:
  port: 8761
  servlet:
    context-path:

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com.netflix:
      eureka: OFF
      discovery: OFF