solr:
  urls:
    - http://solr1:8983/solr
    - http://solr2:8983/solr
    - http://solr3:8983/solr
  zkHosts:
    - zoo1:2181
    - zoo2:2181
    - zoo3:2181
  connectionTimeout: 15000
  socketTimeout: 600000

spring:

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  main:
    lazy-initialization: false
    web-application-type: NONE
