solr:
  urls:
    - http://solr1:8983/solr
    - http://solr2:8983/solr
    - http://solr3:8983/solr
  zk-hosts:
    - zoo1:2181
    - zoo2:2181
    - zoo3:2181
  connection-timeout: 15000
  socket-timeout: 600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka
  instance:
    preferIpAddress: true

spring:

  application:
    name: index

  artemis:
    mode: native
    host: artemis
    port: 61616
    user: artemis
    password: artemis

  jms:
    pub-sub-domain: true

  main:
    lazy-initialization: false
    web-application-type: NONE
