spring:

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

  data:
    solr:
      host: http://localhost:8983/solr

  main:
    web-application-type: NONE
