solr:
  hosts:
    - http://localhost:8981/solr
    - http://localhost:8982/solr
    - http://localhost:8983/solr
  connectionTimeout: 10000
  socketTimeout: 60000

spring:

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

  main:
    web-application-type: NONE
