solr:
  urls:
    - http://localhost:8981/solr
    - http://localhost:8982/solr
    - http://localhost:8983/solr
  zkHosts:
    - localhost:2181
    - localhost:2182
    - localhost:2183
  connectionTimeout: 15000
  socketTimeout: 600000

spring:

  artemis:
    mode: native
    host: localhost
    port: 61616
    user: artemis
    password: artemis

  main:
    web-application-type: NONE
