# https://hub.docker.com/_/solr
#
# docker-compose up
#

version: '3.8'
services:
  solr:
    image: solr:latest
    container_name: solr
    ports:
     - 8983:8983
    environment:
      - ZK_HOST=zoo:2181
      - SOLR_HOST=localhost
    networks:
      - solr
    depends_on:
      - zoo

  zoo:
    image: zookeeper:latest
    container_name: zoo
    restart: always
    hostname: zoo
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181
    networks:
      - solr

networks:
  solr: