# https://hub.docker.com/r/vromero/activemq-artemis
#
# docker build -t artemis .
# docker run -d -p 8161:8161 -p 61616:61616 artemis
#

FROM vromero/activemq-artemis

ENV ARTEMIS_USERNAME artemis
ENV ARTEMIS_PASSWORD artemis